### ISSUE TITLE
More Questions

### ISSUE THREAD

**Issue by Striderzet** [samyanez94/QuizApp#1]
Other than some other things this app may be missing depending on how serious you are about it, it definitely needs more questions. I can add some.

**Comment by samyanez94** [comment]
Hi @Striderzet thanks for your interest in the project. I built QuizApp as a way to improve my iOS knowledge and I'm not intending to release it any time soon. 

If you are interested in adding more questions, please fork the repository and do so! I believe there might also be a few bugs here and there. So, have fun coding! 😬
